<Project Sdk="MSTest.Sdk/3.8.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- 显式确保启用 MTP 原生运行器与 Exe 输出 -->
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../MyApp/MyApp.csproj" />
  </ItemGroup>
</Project>
