<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- 编译为独立的、拥有入口函数（Main 函数）的应用程序。 -->
    <OutputType>Exe</OutputType>
    <!-- 目标运行环境为 .NET 10.0，默认且强制绑定最新的 C# 14 -->
    <TargetFramework>net10.0</TargetFramework>
    <!-- 现代严格模式 -->
    <Nullable>enable</Nullable>
    <!-- 开启 Native AOT，它会自动联锁激活 TrimMode=full、Release下速度优先优化等一系列底层默认值 -->
    <PublishAot>true</PublishAot>
  </PropertyGroup>
</Project>
