<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <OutputType>Exe</OutputType>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
