<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <OutputType>Exe</OutputType>
    <InvariantGlobalization>true</InvariantGlobalization>
    <!-- 允许 Unsafe 代码块：开启对指针和直接内存操作的支持（高性能计算/互操作场景按需启用，默认禁用） -->
    <!-- <AllowUnsafeBlocks>true</AllowUnsafeBlocks> -->
  </PropertyGroup>
</Project>
